---
AWSTemplateFormatVersion: 2010-09-09
Description: Just the dynamo tables to enable dev testing

Resources:

  TemplateSummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: commName
        AttributeType: S
      KeySchema:
      - AttributeName: commName
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TemplateVersionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: commName
        AttributeType: S
      - AttributeName: publishedAt
        AttributeType: N
      KeySchema:
      - AttributeName: commName
        KeyType: HASH
      - AttributeName: publishedAt
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5