version: '2'

services:

  mock-server:
    image: jamesdbloom/mockserver:mockserver-3.12
    ports:
      - "1080:1080"
      - "1090:1090"

  template-manager:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/template-manager:0.1-SNAPSHOT
    depends_on:
      - dynamodb
    command: |
      -Dcomposer.http.endpoint=http://mock-server:1080
    environment:
      ENV: LOCAL
      LOCAL_DYNAMO: "http://dynamodb:8000"
      DOCKER_COMPOSE : "true"
    links:
      - fakes3ssl:ovo-comms-templates.s3-eu-west-1.amazonaws.com
      - fakes3ssl:ovo-comms-templates-raw.s3-eu-west-1.amazonaws.com
      - fakes3ssl:ovo-comms-template-assets.s3-eu-west-1.amazonaws.com
      - mock-server:mock-server
    ports:
      - "9000:9000"
    volumes:
      # share AWS creds so that credstash works
      - $HOME/.aws:/sbin/.aws

  fakes3:
      image: lphoward/fake-s3
      ports:
        - "4569:4569"

  fakes3ssl:
    image: cbachich/ssl-proxy
    depends_on:
      - fakes3
    ports:
      - "443:443"
    links:
      - fakes3:proxyapp
    environment:
      - PORT=443
      - TARGET_PORT=4569

  dynamodb:
      image: forty8bit/dynamodb-local
      ports:
        - "8000:8000"
      entrypoint:
        - "java"
        - "-Djava.library.path=./DynamoDBLocal_lib"
        - "-jar"
        - "DynamoDBLocal.jar"
        - "-sharedDb"
