addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.10")
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.13")
resolvers += Resolver.bintrayIvyRepo("ovotech", "sbt-plugins")
addSbtPlugin("com.ovoenergy" % "sbt-comms-packaging" % "0.0.4")
addSbtPlugin("com.localytics" % "sbt-dynamodb" % "1.5.0")
